import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

/**
 * Persisted metadata for an uploaded image. The binary lives in storage;
 * only its metadata and storage key are kept in the database.
 */
@Entity('images')
export class Image {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Indexed because GET /images filters by title ("title contains {text}").
  @Index()
  @Column({ type: 'varchar', length: 255 })
  title: string;

  /** Storage key (file name) — generated by the app, never user-supplied. */
  @Column({ type: 'varchar', length: 255 })
  storageKey: string;

  @Column({ type: 'int' })
  width: number;

  @Column({ type: 'int' })
  height: number;

  /** Stored image format after processing (e.g. "webp"). */
  @Column({ type: 'varchar', length: 20 })
  format: string;

  @Column({ type: 'int' })
  sizeBytes: number;

  @CreateDateColumn()
  createdAt: Date;
}
