import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { promises as fs } from 'fs';
import { join, resolve, sep } from 'path';
import { StorageService } from './storage.service';

/**
 * Filesystem-backed StorageService.
 *
 * Security notes:
 *  - All access is confined to the configured base directory; `resolveKey`
 *    rejects any key that would escape it (path-traversal guard).
 *  - Keys are generated by the app (UUID-based), never taken from user input.
 */
@Injectable()
export class LocalStorageService extends StorageService implements OnModuleInit {
  private readonly logger = new Logger(LocalStorageService.name);
  private readonly baseDir: string;

  constructor(config: ConfigService) {
    super();
    this.baseDir = resolve(config.get<string>('storageDir', './storage'));
  }

  async onModuleInit(): Promise<void> {
    await fs.mkdir(this.baseDir, { recursive: true });
    this.logger.log(`Local storage ready at ${this.baseDir}`);
  }

  async save(key: string, data: Buffer): Promise<string> {
    const path = this.resolveKey(key);
    await fs.writeFile(path, data);
    return key;
  }

  async read(key: string): Promise<Buffer> {
    return fs.readFile(this.resolveKey(key));
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.resolveKey(key));
      return true;
    } catch {
      return false;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await fs.unlink(this.resolveKey(key));
    } catch (err) {
      // best-effort cleanup — log but do not throw
      this.logger.warn(`Failed to delete "${key}": ${(err as Error).message}`);
    }
  }

  /** Resolve a key to an absolute path, guaranteeing it stays inside baseDir. */
  private resolveKey(key: string): string {
    const path = resolve(join(this.baseDir, key));
    if (path !== this.baseDir && !path.startsWith(this.baseDir + sep)) {
      throw new Error(`Path traversal attempt blocked for key "${key}"`);
    }
    return path;
  }
}
